/**
 * Compile the LinkedIn shape library from callcraft's creator CSVs.
 *
 * Reads the three ACX creator exports (~3,150 posts), keeps only substantive
 * bodies, ranks by likes, and vendors the top posts per creator into
 * src/writer/shape-library.generated.ts. The selection is engagement-measured,
 * not taste-guessed — the whole point is that the corpus tells us what shape
 * performs, per the founder's 2026-08-06 direction to build on it at every
 * level.
 *
 * The generated file carries whole bodies as STRUCTURE references. The lock
 * that facts, offers, names and phrases never transfer lives beside them in
 * the runtime prompt (src/writer/write.ts), same rule as the founder exemplar.
 *
 * Run: npx tsx scripts/compile-shape-library.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SOURCE_DIR =
  process.env.TALLTRACK_CREATOR_CSV_DIR ??
  '/Users/satyaphanindra/Desktop/callcraft/references posts'

const SOURCES = [
  { creator: 'Ruben Hassid', file: 'LI Creators Post - ACX - Ruben Hassid.csv' },
  { creator: 'Michel Lieben', file: 'LI Creators Post - ACX - Michel Lieben.csv' },
  { creator: 'Jake Ward', file: 'LI Creators Post - ACX - Jake Ward.csv' },
]

const PER_CREATOR = 8
const MIN_CHARS = 400
const MAX_CHARS = 2200

// Minimal CSV parser that handles quoted fields with embedded newlines —
// the post bodies are full multi-line LinkedIn posts.
function parseCsv(text: string): string[][] {
  const rows: string[][] = []
  let row: string[] = []
  let field = ''
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"'
          i++
        } else inQuotes = false
      } else field += ch
    } else if (ch === '"') inQuotes = true
    else if (ch === ',') {
      row.push(field)
      field = ''
    } else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++
      row.push(field)
      field = ''
      if (row.some((f) => f.length > 0)) rows.push(row)
      row = []
    } else field += ch
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field)
    if (row.some((f) => f.length > 0)) rows.push(row)
  }
  return rows
}

type Entry = { creator: string; likes: number; body: string }

const picked: Entry[] = []
for (const { creator, file } of SOURCES) {
  const rows = parseCsv(readFileSync(join(SOURCE_DIR, file), 'utf8'))
  const header = rows[0] ?? []
  const contentIdx = header.indexOf('content')
  const likesIdx = header.indexOf('engagement/likes')
  const seen = new Set<string>()
  const candidates: Entry[] = []
  for (const r of rows.slice(1)) {
    const body = (r[contentIdx] ?? '').trim()
    const likes = Number(r[likesIdx] ?? 0) || 0
    if (body.length < MIN_CHARS || body.length > MAX_CHARS) continue
    const key = body.slice(0, 80)
    if (seen.has(key)) continue
    seen.add(key)
    candidates.push({ creator, likes, body })
  }
  candidates.sort((a, b) => b.likes - a.likes)
  picked.push(...candidates.slice(0, PER_CREATOR))
}

const out = `// GENERATED by scripts/compile-shape-library.ts — do not edit by hand.
// Top ${PER_CREATOR} posts per creator by likes from callcraft's ACX creator CSVs.
// STRUCTURE references only: the runtime prompt forbids reusing their facts,
// names, offers, hooks or phrases. Re-run the script when the CSVs change.

export type ShapeReference = { creator: string; likes: number; body: string }

export const SHAPE_LIBRARY: ShapeReference[] = ${JSON.stringify(picked, null, 2)}
`
writeFileSync(join(import.meta.dirname, '../src/writer/shape-library.generated.ts'), out)
console.log(
  `Wrote ${picked.length} shape references (${picked.map((p) => p.likes).reduce((a, b) => Math.min(a, b))}–${picked
    .map((p) => p.likes)
    .reduce((a, b) => Math.max(a, b))} likes).`,
)
