// GENERATED by scripts/compile-linkedin-reference-corpus.ts
// Policy: linkedin-reference-blueprint-v3
// Source post text is intentionally absent. Do not hand-edit.

export type GeneratedLinkedInReferenceBlueprint = {
  readonly id: string
  readonly cohort: 'source-a' | 'source-b'
  readonly callFit: 'sales-conversation' | 'objection-dialogue' | 'buyer-decision' | 'sales-process' | 'none'
  readonly direction: 'story' | 'argument' | 'process' | 'list' | 'proof' | 'lesson'
  readonly hookMechanism: 'how-to promise' | 'first-person scene' | 'contrarian claim' | 'outcome-led claim' | 'decision-stake assertion' | 'direct assertion'
  readonly tensionMechanism: 'buyer objection' | 'costly constraint' | 'expectation gap' | 'decision tradeoff' | 'unresolved consequence'
  readonly turnMechanism: 'evidence-backed proof' | 'changed interpretation' | 'decision rule' | 'sequence payoff' | 'earned realization'
  readonly beatMap: readonly string[]
  readonly bodyMovement: string
  readonly evidenceRole: string
  readonly endingMove: 'micro-action' | 'decision rule' | 'callback' | 'earned takeaway'
  readonly paragraphRhythm: 'mixed short blocks' | 'prose-led blocks'
  readonly targetWords: 230 | 300
  readonly specificitySlots: readonly string[]
}

export const GENERATED_LINKEDIN_REFERENCE_BLUEPRINTS = [
  {
    "id": "ref-016fda4dc4cd55d51b",
    "cohort": "source-a",
    "direction": "story",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "unresolved consequence",
    "turnMechanism": "earned realization",
    "beatMap": [
      "specific scene",
      "felt friction",
      "consequence",
      "earned realization",
      "reader bridge",
      "quiet landing"
    ],
    "bodyMovement": "specific scene → felt friction → consequence → earned realization → reader bridge → quiet landing",
    "evidenceRole": "one bounded scene carries the tension and turn",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "bounded scene"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-060368a89a8a4e8c08",
    "cohort": "source-b",
    "direction": "process",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "expectation gap",
    "turnMechanism": "changed interpretation",
    "beatMap": [
      "specific problem",
      "stakes",
      "ordered moves",
      "reason each move works",
      "decision checkpoint",
      "earned result"
    ],
    "bodyMovement": "specific problem → stakes → ordered moves → reason each move works → decision checkpoint → earned result",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "mixed short blocks",
    "targetWords": 300,
    "specificitySlots": [
      "contrast"
    ],
    "callFit": "sales-process"
  },
  {
    "id": "ref-07077532a7cf315004",
    "cohort": "source-a",
    "direction": "argument",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "recognizable belief",
      "counterclaim",
      "concrete proof",
      "mechanism",
      "decision rule",
      "owned landing"
    ],
    "bodyMovement": "recognizable belief → counterclaim → concrete proof → mechanism → decision rule → owned landing",
    "evidenceRole": "specific proof establishes the turn before the implication",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 230,
    "specificitySlots": [
      "concrete proof",
      "contrast",
      "consequence"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-0860ae419f77477269",
    "cohort": "source-b",
    "direction": "list",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "buyer objection",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "single thesis",
      "selection criterion",
      "parallel observations",
      "consequence per item",
      "synthesis",
      "decision rule"
    ],
    "bodyMovement": "single thesis → selection criterion → parallel observations → consequence per item → synthesis → decision rule",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "mixed short blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof",
      "buyer objection",
      "contrast"
    ],
    "callFit": "objection-dialogue"
  },
  {
    "id": "ref-0c81a6b3d77f0f6d2d",
    "cohort": "source-b",
    "direction": "proof",
    "hookMechanism": "outcome-led claim",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "concrete outcome",
      "before-state",
      "constraint",
      "mechanism",
      "evidence-backed turn",
      "reader implication"
    ],
    "bodyMovement": "concrete outcome → before-state → constraint → mechanism → evidence-backed turn → reader implication",
    "evidenceRole": "a bounded scene earns the before-and-after claim",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "bounded scene",
      "concrete proof",
      "contrast",
      "consequence"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-0f543b7c4e0d194388",
    "cohort": "source-a",
    "direction": "story",
    "hookMechanism": "outcome-led claim",
    "tensionMechanism": "expectation gap",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "specific scene",
      "expected outcome",
      "felt friction",
      "contrast",
      "reader bridge",
      "quiet landing"
    ],
    "bodyMovement": "specific scene → expected outcome → felt friction → contrast → reader bridge → quiet landing",
    "evidenceRole": "one bounded scene carries the tension and turn",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "bounded scene",
      "concrete proof",
      "contrast"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-201d8382833931fe65",
    "cohort": "source-b",
    "direction": "process",
    "hookMechanism": "how-to promise",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "specific problem",
      "stakes",
      "ordered moves",
      "reason each move works",
      "decision checkpoint",
      "earned result"
    ],
    "bodyMovement": "specific problem → stakes → ordered moves → reason each move works → decision checkpoint → earned result",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof",
      "contrast",
      "consequence"
    ],
    "callFit": "sales-process"
  },
  {
    "id": "ref-21230646116afda449",
    "cohort": "source-a",
    "direction": "proof",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "expectation gap",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "concrete outcome",
      "before-state",
      "constraint",
      "mechanism",
      "evidence-backed turn",
      "reader implication"
    ],
    "bodyMovement": "concrete outcome → before-state → constraint → mechanism → evidence-backed turn → reader implication",
    "evidenceRole": "specific proof establishes the turn before the implication",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof",
      "contrast"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-27c97b2cf18dace26b",
    "cohort": "source-b",
    "direction": "lesson",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "changed interpretation",
    "beatMap": [
      "specific observation",
      "expected explanation",
      "contradicting detail",
      "changed interpretation",
      "reader criterion",
      "earned takeaway"
    ],
    "bodyMovement": "specific observation → expected explanation → contradicting detail → changed interpretation → reader criterion → earned takeaway",
    "evidenceRole": "the contrasting detail earns the changed interpretation",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 230,
    "specificitySlots": [
      "contrast",
      "consequence"
    ],
    "callFit": "sales-process"
  },
  {
    "id": "ref-2cd78633ab4c232c5e",
    "cohort": "source-b",
    "direction": "process",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "unresolved consequence",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "specific problem",
      "stakes",
      "ordered moves",
      "reason each move works",
      "decision checkpoint",
      "earned result"
    ],
    "bodyMovement": "specific problem → stakes → ordered moves → reason each move works → decision checkpoint → earned result",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "mixed short blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof"
    ],
    "callFit": "sales-conversation"
  },
  {
    "id": "ref-316bb5a823ae154e31",
    "cohort": "source-b",
    "direction": "list",
    "hookMechanism": "outcome-led claim",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "single thesis",
      "selection criterion",
      "parallel observations",
      "consequence per item",
      "synthesis",
      "decision rule"
    ],
    "bodyMovement": "single thesis → selection criterion → parallel observations → consequence per item → synthesis → decision rule",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "mixed short blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof",
      "contrast",
      "consequence"
    ],
    "callFit": "buyer-decision"
  },
  {
    "id": "ref-3818fe51ec3b2e2a1a",
    "cohort": "source-a",
    "direction": "story",
    "hookMechanism": "first-person scene",
    "tensionMechanism": "unresolved consequence",
    "turnMechanism": "earned realization",
    "beatMap": [
      "specific scene",
      "felt friction",
      "consequence",
      "earned realization",
      "reader bridge",
      "quiet landing"
    ],
    "bodyMovement": "specific scene → felt friction → consequence → earned realization → reader bridge → quiet landing",
    "evidenceRole": "one bounded scene carries the tension and turn",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "bounded scene"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-4a98d322427f70fc3e",
    "cohort": "source-b",
    "direction": "process",
    "hookMechanism": "outcome-led claim",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "specific problem",
      "stakes",
      "ordered moves",
      "reason each move works",
      "decision checkpoint",
      "earned result"
    ],
    "bodyMovement": "specific problem → stakes → ordered moves → reason each move works → decision checkpoint → earned result",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof",
      "contrast",
      "consequence"
    ],
    "callFit": "sales-conversation"
  },
  {
    "id": "ref-739bff9fc2e5d27961",
    "cohort": "source-a",
    "direction": "proof",
    "hookMechanism": "outcome-led claim",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "concrete outcome",
      "before-state",
      "constraint",
      "mechanism",
      "evidence-backed turn",
      "reader implication"
    ],
    "bodyMovement": "concrete outcome → before-state → constraint → mechanism → evidence-backed turn → reader implication",
    "evidenceRole": "specific proof establishes the turn before the implication",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof",
      "contrast",
      "consequence"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-8111cb91be75dc56e4",
    "cohort": "source-b",
    "direction": "lesson",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "decision tradeoff",
    "turnMechanism": "decision rule",
    "beatMap": [
      "specific observation",
      "expected explanation",
      "contradicting detail",
      "changed interpretation",
      "reader criterion",
      "earned takeaway"
    ],
    "bodyMovement": "specific observation → expected explanation → contradicting detail → changed interpretation → reader criterion → earned takeaway",
    "evidenceRole": "the contrasting detail earns the changed interpretation",
    "endingMove": "callback",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 230,
    "specificitySlots": [
      "decision criterion",
      "contrast"
    ],
    "callFit": "sales-conversation"
  },
  {
    "id": "ref-85419a208c7bb20ad5",
    "cohort": "source-a",
    "direction": "process",
    "hookMechanism": "how-to promise",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "changed interpretation",
    "beatMap": [
      "specific problem",
      "stakes",
      "ordered moves",
      "reason each move works",
      "decision checkpoint",
      "earned result"
    ],
    "bodyMovement": "specific problem → stakes → ordered moves → reason each move works → decision checkpoint → earned result",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "contrast",
      "consequence"
    ],
    "callFit": "sales-process"
  },
  {
    "id": "ref-a22a729c95d574a3c9",
    "cohort": "source-a",
    "direction": "story",
    "hookMechanism": "first-person scene",
    "tensionMechanism": "expectation gap",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "specific scene",
      "expected outcome",
      "felt friction",
      "contrast",
      "reader bridge",
      "quiet landing"
    ],
    "bodyMovement": "specific scene → expected outcome → felt friction → contrast → reader bridge → quiet landing",
    "evidenceRole": "one bounded scene carries the tension and turn",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "mixed short blocks",
    "targetWords": 300,
    "specificitySlots": [
      "bounded scene",
      "concrete proof",
      "contrast"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-a31dc61fa9be542cee",
    "cohort": "source-b",
    "direction": "process",
    "hookMechanism": "outcome-led claim",
    "tensionMechanism": "unresolved consequence",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "specific problem",
      "stakes",
      "ordered moves",
      "reason each move works",
      "decision checkpoint",
      "earned result"
    ],
    "bodyMovement": "specific problem → stakes → ordered moves → reason each move works → decision checkpoint → earned result",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof"
    ],
    "callFit": "sales-process"
  },
  {
    "id": "ref-b400851edc25f7a7da",
    "cohort": "source-a",
    "direction": "process",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "expectation gap",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "specific problem",
      "stakes",
      "ordered moves",
      "reason each move works",
      "decision checkpoint",
      "earned result"
    ],
    "bodyMovement": "specific problem → stakes → ordered moves → reason each move works → decision checkpoint → earned result",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "mixed short blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof",
      "contrast"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-cb2d8597381faf8816",
    "cohort": "source-a",
    "direction": "lesson",
    "hookMechanism": "decision-stake assertion",
    "tensionMechanism": "costly constraint",
    "turnMechanism": "changed interpretation",
    "beatMap": [
      "specific observation",
      "expected explanation",
      "contradicting detail",
      "changed interpretation",
      "reader criterion",
      "earned takeaway"
    ],
    "bodyMovement": "specific observation → expected explanation → contradicting detail → changed interpretation → reader criterion → earned takeaway",
    "evidenceRole": "the contrasting detail earns the changed interpretation",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 230,
    "specificitySlots": [
      "contrast",
      "consequence"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-d241fbace7fd04bf5a",
    "cohort": "source-a",
    "direction": "argument",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "expectation gap",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "recognizable belief",
      "counterclaim",
      "concrete proof",
      "mechanism",
      "decision rule",
      "owned landing"
    ],
    "bodyMovement": "recognizable belief → counterclaim → concrete proof → mechanism → decision rule → owned landing",
    "evidenceRole": "specific proof establishes the turn before the implication",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 230,
    "specificitySlots": [
      "concrete proof",
      "contrast"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-d3c2eeaf7edd1c0a6e",
    "cohort": "source-b",
    "direction": "process",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "expectation gap",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "specific problem",
      "stakes",
      "ordered moves",
      "reason each move works",
      "decision checkpoint",
      "earned result"
    ],
    "bodyMovement": "specific problem → stakes → ordered moves → reason each move works → decision checkpoint → earned result",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof",
      "contrast"
    ],
    "callFit": "sales-process"
  },
  {
    "id": "ref-e513481d18a22e0854",
    "cohort": "source-a",
    "direction": "list",
    "hookMechanism": "direct assertion",
    "tensionMechanism": "unresolved consequence",
    "turnMechanism": "evidence-backed proof",
    "beatMap": [
      "single thesis",
      "selection criterion",
      "parallel observations",
      "consequence per item",
      "synthesis",
      "decision rule"
    ],
    "bodyMovement": "single thesis → selection criterion → parallel observations → consequence per item → synthesis → decision rule",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "mixed short blocks",
    "targetWords": 300,
    "specificitySlots": [
      "concrete proof"
    ],
    "callFit": "none"
  },
  {
    "id": "ref-fab391739c7659b0d0",
    "cohort": "source-b",
    "direction": "list",
    "hookMechanism": "decision-stake assertion",
    "tensionMechanism": "expectation gap",
    "turnMechanism": "changed interpretation",
    "beatMap": [
      "single thesis",
      "selection criterion",
      "parallel observations",
      "consequence per item",
      "synthesis",
      "decision rule"
    ],
    "bodyMovement": "single thesis → selection criterion → parallel observations → consequence per item → synthesis → decision rule",
    "evidenceRole": "each ordered item must advance one causal thesis",
    "endingMove": "earned takeaway",
    "paragraphRhythm": "prose-led blocks",
    "targetWords": 300,
    "specificitySlots": [
      "contrast"
    ],
    "callFit": "sales-process"
  }
] as const satisfies readonly GeneratedLinkedInReferenceBlueprint[]
